spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    generate-ddl: true


movie:
  box:
    key: 38b6115a994d498ad200a534627cf969


naver:
  url:
    search:
      movie: https://openapi.naver.com/v1/search/local.json

    client:
      id: 13De2BDkkPwBrZddTNyQ
      secret: 5z043okjEz

